---
- name: Install sensu packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ sensu_apt_package }}"
    - "{{ sensu_apt_dependencies }}"

- block: # Ensuring services
  - name: Ensure sensu server service enabled
    service:
      name: sensu-server
      enabled: yes
      state: started
    when: sensu_checks

  - name: Ensure sensu api service enabled
    service:
      name: sensu-api
      enabled: yes
      state: started
    when: sensu_api

  - name: Ensure sensu client service enabled
    service:
      name: sensu-client
      enabled: yes
      state: started
    when: sensu_client