---
- name: Copy sensu configuration file
  template:
    src: "{{ sensu_host_config_file_path }}"
    dest: "{{ sensu_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: sensu_config_check.stat.exists
  notify:
    - Restart sensu server
    - Restart sensu client

- name: Copy SSL certificates directory
  copy:
    src: "{{ sensu_host_config_path }}/ssl"
    dest: "{{ sensu_config_path }}/"
  when:
    - sensu_config_ssl_check.stat.isdir is defined
    - sensu_config_ssl_check.stat.isdir
  notify: 
    - Restart sensu server
    - Restart sensu api
    - Restart sensu client

- block: # Dynamic configuration style
  - name: Drop sensu configuration file(s)
    template:
      src: config.json.j2
      dest: "{{ sensu_config_file_path }}"
    when: not sensu_config_check.stat.exists
    notify: 
      - Restart sensu server
      - Restart sensu client

- meta: flush_handlers